### PR TITLE
Create Learning Path “cyber-security-course”

### PR DESCRIPTION
**Pull request by tallurikris**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by irenekurien** [comment]
We already have a Cyber Security learning path, could you please add the contents to that?

**Review by gautamkrishnar — DISMISSED** [review]
LGTM 👍🏻

**Comment by gautamkrishnar** [comment]
Contents look good to me, Please move the contribution to the existing cybersecurity course.

**Comment by akhilmhdh** [comment]
Great addition to the content but this should be just a section rather than a whole learning path. AS @irenekurien  suggested cyber security learning path is already exist kindly add this section to there. It will improve the contents value.

**Comment by gautamkrishnar** [comment]
@irenekurien can you please do this yourself, take this commit and make it part of the main article?

**Comment by gautamkrishnar** [comment]
Merged as the part of #129

**Pull request closed without merging**
